language: php
php:
- '7.0'
script: echo "We don't have tests yet :("
before_deploy:
- sh config.sh
- sh package.sh
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key: $GITHUB_TOKEN
  file: plugin-transbank-webpay-rest-opencart3-$TRAVIS_TAG.ocmod.zip
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-opencart-webpay-rest
    tags: true
